# Generated by Django 3.1.3 on 2020-11-29 14:42

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.core.fields.StreamField([('column_wide_image', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True))])))])), ('cta', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Learn More', max_length=80, required=True))])), ('left_card_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=80, required=True)), ('text', wagtail.core.blocks.TextBlock(required=True)), ('richtext', wagtail.core.blocks.RichTextBlock(required=True)), ('button', wagtail.core.blocks.StructBlock([('button_title', wagtail.core.blocks.CharBlock(help_text='Enter text to be displayed on the button', required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='If the button page is selected, that will be used instead', required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False))]))])))])), ('full_richtext', streams.blocks.RichtextBlock()), ('right_card_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=80, required=True)), ('text', wagtail.core.blocks.TextBlock(required=True)), ('richtext', wagtail.core.blocks.RichTextBlock(required=True)), ('button', wagtail.core.blocks.StructBlock([('button_title', wagtail.core.blocks.CharBlock(help_text='Enter text to be displayed on the button', required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='If the button page is selected, that will be used instead', required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False))]))])))])), ('three_image_block', wagtail.core.blocks.StructBlock([('image_cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image_one', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_two', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_three', wagtail.images.blocks.ImageChooserBlock(required=True))])))])), ('two_column_text', wagtail.core.blocks.StructBlock([('column_one_text', wagtail.core.blocks.RichTextBlock(required=True)), ('column_two_text', wagtail.core.blocks.RichTextBlock(required=True))])), ('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional text', required=True))])), ('two_image_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('lead_text', wagtail.core.blocks.TextBlock(help_text='Add your lead text', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional text', required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('image_cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image_one', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image_two', wagtail.images.blocks.ImageChooserBlock(required=True))])))]))], blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Flex Page',
                'verbose_name_plural': 'Flex Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
